version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
      - image: mongo:4.0.4
    steps:
      - checkout
      - run:
        name: setup
        command: |
          npm run now-build
