version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
      - image: mongo:4.0.4
    steps:
      - checkout
      - run:
          name: setup
          command: "yarn run now-build"
      - run:
          name: install-now
          command: "yarn global add now"
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
